version: '3.6'
services:
  metaractor:
    build: .
    image: outstand/metaractor:dev
    stdin_open: true
    tty: true
    volumes:
      - bundler-data:/usr/local/bundle
      - .:/metaractor
volumes:
  bundler-data:
