version: '3.6'
services:
  metaractor:
    build: .
    image: outstand/metaractor:dev
    stdin_open: true
    tty: true
    environment:
      FIXUID:
      FIXGID:
      BUILDKITE:
      BUILDKITE_BUILD_URL:
      BUILDKITE_JOB_ID:
      BUILDKITE_AGENT_ACCESS_TOKEN:
    volumes:
      - bundler-data:/usr/local/bundle
      - .:/metaractor
  release:
    image: outstand/metaractor:dev
    stdin_open: true
    tty: true
    command: rake release
    environment:
      FIXUID:
      FIXGID:
    volumes:
      - bundler-data:/usr/local/bundle
      - ~/.gitconfig:/home/metaractor/.gitconfig
      - ~/.gitconfig.user:/home/metaractor/.gitconfig.user
      - ~/.ssh/id_rsa:/home/metaractor/.ssh/id_rsa
      - ~/.gem:/home/metaractor/.gem

volumes:
  bundler-data:
