env:
  BUILDKITE_PLUGIN_DOCKER_CACHE_S3_BUCKET: "outstand-buildkite-cache"
  # BUILDKITE_PLUGIN_DOCKER_CACHE_VOLUME_DEBUG: "true"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_SHELL: "false"
  # BUILDKITE_PLUGIN_DOCKER_COMPOSE_UPLOAD_CONTAINER_LOGS: "always"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_PULL_RETRIES: 5
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_PUSH_RETRIES: 5
  PLUGIN_DOCKER_COMPOSE_VERSION: "e88235edd25e436a810da1ce161c04237c7a6f2c"
  PLUGIN_DOCKER_CACHE_VERSION: "ffd18c5910ad402493e8a6614536b4e2b286d665"

steps:
  - label: ":docker: Build"
    key: build
    plugins:
      - seek-oss/aws-sm#v2.2.1:
          env:
            DOCKER_LOGIN_PASSWORD: "/buildkite/docker_password"

      - docker-login#v2.0.1:
          username: outstandci

      - ecr#v2.1.1:
          login: true
          region: "us-east-1"

      - https://github.com/outstand/docker-compose-buildkite-plugin.git#${PLUGIN_DOCKER_COMPOSE_VERSION}:
          build: metaractor
          image-repository: 786715713882.dkr.ecr.us-east-1.amazonaws.com/ci-images
          config:
            - docker-compose.yml

  - label: ":bundler: :rubygems:"
    key: bundle_install
    command: bundle install
    depends_on: build
    plugins:
      - seek-oss/aws-sm#v2.2.1:
          env:
            DOCKER_LOGIN_PASSWORD: "/buildkite/docker_password"

      - docker-login#v2.0.1:
          username: outstandci

      - ecr#v2.1.1:
          login: true
          region: "us-east-1"

      - https://github.com/outstand/docker-compose-buildkite-plugin.git#${PLUGIN_DOCKER_COMPOSE_VERSION}:
          run: metaractor
          dependencies: false
          config:
            - docker-compose.yml

      - https://github.com/outstand/docker-cache-buildkite-plugin.git#${PLUGIN_DOCKER_CACHE_VERSION}:
          name: bundler-cache
          keys:
            - v1-bundler-cache-{{ arch }}-{{ checksum "metaractor.gemspec" }}-{{ checksum "Gemfile" }}
            - v1-bundler-cache-{{ arch }}-
          save: true
          volumes:
            - bundler-data

  - label: ":ruby: Specs"
    command: rspec spec
    depends_on: bundle_install
    plugins:
      - seek-oss/aws-sm#v2.2.1:
          env:
            DOCKER_LOGIN_PASSWORD: "/buildkite/docker_password"
          json-to-env:
            - secret-id: "/buildkite/rails/env_vars"

      - docker-login#v2.0.1:
          username: outstandci

      - ecr#v2.1.1:
          login: true
          region: "us-east-1"

      - https://github.com/outstand/docker-compose-buildkite-plugin.git#${PLUGIN_DOCKER_COMPOSE_VERSION}:
          run: metaractor
          config:
            - docker-compose.yml

      - https://github.com/outstand/docker-cache-buildkite-plugin.git#${PLUGIN_DOCKER_CACHE_VERSION}:
          name: bundler-cache
          keys:
            - v1-bundler-cache-{{ arch }}-{{ checksum "metaractor.gemspec" }}-{{ checksum "Gemfile" }}
            - v1-bundler-cache-{{ arch }}-
          volumes:
            - bundler-data
