env:
  BUILDKITE_PLUGIN_DOCKER_CACHE_S3_BUCKET: "outstand-buildkite-cache"
  # BUILDKITE_PLUGIN_DOCKER_CACHE_VOLUME_DEBUG: "true"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_SHELL: "false"
  # BUILDKITE_PLUGIN_DOCKER_COMPOSE_UPLOAD_CONTAINER_LOGS: "always"
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_PULL_RETRIES: 5
  BUILDKITE_PLUGIN_DOCKER_COMPOSE_PUSH_RETRIES: 5
  PLUGIN_DOCKER_COMPOSE_VERSION: "03d746fbf5171b217b732ff7d8a3e417d664df1c"
  PLUGIN_DOCKER_CACHE_VERSION: "50ecc80f736a4a3a0ab1f5990e58ae8e536c85e1"
  WORKSPACE_DIR: "${BUILDKITE_BUILD_CHECKOUT_PATH}"

steps:
  - label: ":docker: Build"
    key: build
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            DOCKER_LOGIN_PASSWORD: "/buildkite/docker_password"

      - docker-login#v2.1.0:
          username: outstandci
          retries: 2

      - ecr#v2.5.0:
          login: true
          region: "us-east-1"

      - https://github.com/outstand/docker-compose-buildkite-plugin.git#${PLUGIN_DOCKER_COMPOSE_VERSION}:
          build: metaractor
          image-repository: 786715713882.dkr.ecr.us-east-1.amazonaws.com/ci-images
          config:
            - compose.yml

  - label: ":bundler: :rubygems:"
    key: bundle_install
    command: bundle install
    depends_on: build
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            DOCKER_LOGIN_PASSWORD: "/buildkite/docker_password"

      - docker-login#v2.1.0:
          username: outstandci
          retries: 2

      - ecr#v2.5.0:
          login: true
          region: "us-east-1"

      - https://github.com/outstand/docker-compose-buildkite-plugin.git#${PLUGIN_DOCKER_COMPOSE_VERSION}:
          run: metaractor
          dependencies: false
          config:
            - compose.yml

      - https://github.com/outstand/docker-cache-buildkite-plugin.git#${PLUGIN_DOCKER_CACHE_VERSION}:
          name: bundler-cache
          keys:
            - v2-bundler-cache-{{ arch }}-{{ checksum "metaractor.gemspec" }}-{{ checksum "Gemfile" }}
            - v2-bundler-cache-{{ arch }}-
          save: true
          volumes:
            - bundler-data

  - label: ":ruby: Specs"
    command: rspec spec
    depends_on: bundle_install
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          env:
            DOCKER_LOGIN_PASSWORD: "/buildkite/docker_password"

      - docker-login#v2.1.0:
          username: outstandci
          retries: 2

      - ecr#v2.5.0:
          login: true
          region: "us-east-1"

      - https://github.com/outstand/docker-compose-buildkite-plugin.git#${PLUGIN_DOCKER_COMPOSE_VERSION}:
          run: metaractor
          config:
            - compose.yml

      - https://github.com/outstand/docker-cache-buildkite-plugin.git#${PLUGIN_DOCKER_CACHE_VERSION}:
          name: bundler-cache
          keys:
            - v2-bundler-cache-{{ arch }}-{{ checksum "metaractor.gemspec" }}-{{ checksum "Gemfile" }}
            - v2-bundler-cache-{{ arch }}-
          volumes:
            - bundler-data
