name: Release

on:
  workflow_dispatch:

jobs:
  push:
    name: Push gem
    runs-on: ubuntu-latest

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # IMPORTANT: this permission is required for `rake release` to push the release tag

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          ruby-version: ruby # Use latest ruby

      - name: Set Environment Variables
        run: |
          version=$(ruby -e 'require_relative "lib/metaractor/version.rb"; puts Metaractor.version')
          echo "APP_VERSION=$version" >> $GITHUB_ENV

      # Release
      - uses: rubygems/release-gem@v1

      # GitHub release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "pkg/*.gem"
          generateReleaseNotes: true
          skipIfReleaseExists: true
          tag: ${{ env.APP_VERSION }}
